workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials
      vars:
        APP_ID: com.repoverse.app
        BUNDLE_ID: com.repoverse.app
    scripts:
      - name: Navigate to Flutter app directory
        script: |
          cd RepoFinderMobile
      - name: Get Flutter dependencies
        script: |
          cd RepoFinderMobile
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd RepoFinderMobile/ios
          pod install
      - name: Set up code signing settings on Xcode project
        script: |
          cd RepoFinderMobile
          xcode-project use-profiles
          xcode-project set-identity
          # Verify bundle ID is correct
          /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier com.repoverse.app" ios/Runner/Info.plist || true
      - name: Build ipa for distribution
        script: |
          cd RepoFinderMobile
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=1
    artifacts:
      - RepoFinderMobile/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - mandanajignesh@gmail.com
        notify:
          success: true
          failure: false
      # App Store Connect publishing (uncomment when ready to submit to TestFlight)
      # app_store_connect:
      #   auth: integration
      #   submit_to_testflight: true
